version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Create virtualenv
          command: python -m venv venv
      - run:
          name: Install requirements
          command: |
            source venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Recreate DB
          command: |
            source venv/bin/activate
            python recreate_db.py

  test:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Create virtualenv
          command: python -m venv venv
      - run:
          name: Install requirements
          command: |
            source venv/bin/activate
            pip install -r requirements.txt

      - run:
          name: Run tests
          command: |
            source venv/bin/activate
            pytest -s

  deploy:
    working_directory: ~/project
    docker:
      - image: docker:19.03
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: install dependencies
          command: |
            apk add curl bash git
            apk add --update nodejs nodejs-npm
            npm config set unsafe-perm true
            npm install -g heroku
      - run:
          name: show author
          command: |
            ACRONYM=$(echo $CIRCLE_BRANCH | awk -F_ '{print $NF}')
            API_KEY_VAR_NAME=$(echo HEROKU_API_KEY_$ACRONYM | awk '{ print toupper($0) }')
            HEROKU_APP_SUFFIX=$(echo $ACRONYM | awk '{ print tolower($0) }')

            # echo $API_KEY_VAR_NAME
            # echo $HEROKU_APP_SUFFIX

            HEROKU_API_KEY=${!API_KEY_VAR_NAME}
            heroku container:login
            heroku container:push web -a $HEROKU_APP_SUFFIX
            heroku container:release web -a $HEROKU_APP_SUFFIX

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
            



